# Generated by Django 3.2.9 on 2021-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, null=True)),
                ('platform', models.TextField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('genre', models.TextField(max_length=100, null=True)),
                ('Publisher', models.TextField(max_length=100, null=True)),
                ('NA_Sales', models.FloatField()),
                ('EU_Sales', models.FloatField()),
                ('JP_Sales', models.FloatField()),
                ('Other_Sales', models.FloatField()),
                ('Global_Sales', models.FloatField()),
            ],
        ),
    ]
