# Generated by Django 3.2.9 on 2021-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20211206_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
