# Generated by Django 3.2.9 on 2021-12-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Publisher',
            new_name='publisher',
        ),
    ]
