# Generated by Django 3.2.9 on 2021-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0007_alter_game_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
